amplify-education/terrawrap

README.md, bin/backend_check, setup.py, terrawrap/version.py
Added a new check command that verifies all terraform config directories
have a backend defined.
=> AT-1401 Add backend_check Command

bin/tf, mypy.ini, package.json, terrawrap/utils/config.py, terrawrap/utils/module.py, terrawrap/utils/path.py, terrawrap/utils/tf_variables.py, terrawrap/version.py, test-requirements.pip, tox.ini
=> Don't assume bucket name when updating digest

bin/pipeline_check, bin/plan_check, bin/tf, bin/tf_apply, terrawrap/models/pipeline.py, terrawrap/utils/cli.py, terrawrap/utils/dynamodb.py, terrawrap/version.py
Now that we are on python3, let's add more typing!
=> Additional Typing

bin/backend_check, bin/pipeline_check, terrawrap/utils/config.py, terrawrap/version.py
Rewrite pipeline_check to accept a list of paths to constrain its results
and remove hardcoded paths
Rewrite backend_check to accept paths to contrain the checks to
=> Rewrite Commit Checks

terrawrap/utils/cli.py, terrawrap/utils/config.py, terrawrap/version.py
The old behavior was to error out
=> Replace characters with ? when we get unicode errors

bin/backend_check, terrawrap/exceptions.py, terrawrap/utils/config.py, terrawrap/version.py
Skip directories that don't contain terraform files during backend_check
=> Fix backend check

terrawrap/utils/cli.py, terrawrap/version.py
Found another throttle error from Terraform.
=> BugFix: Retry Another Throttle Error

CHANGELOG.md, bin/graph_apply, bin/plan_check, terrawrap/exceptions.py, terrawrap/utils/config.py, terrawrap/utils/graph.py, terrawrap/version.py
The `connect_symlinks` does not read `.tf_wrapper` and add folders to run.
Add temporary fix for checking `.tf_wrapper`
=> Fix graph_apply for symlinked configs

requirements.pip, terrawrap/version.py
=> Revert "update jsons package version"

CHANGELOG.md, requirements.pip, terrawrap/version.py
Version >= 1.2.0 raises an error
I have checked with version jsons>=1.0.0,<1.2.0 and it works fine
https://github.com/ramonhagenaars/jsons
=> Update jsons package

requirements.pip, setup.py, terrawrap/utils/module.py, terrawrap/utils/path.py, terrawrap/utils/tf_variables.py, terrawrap/version.py, tox.ini
also add support for python 3.9
=> Change plan check to ignore git directory

terrawrap/utils/version.py, terrawrap/version.py
let's try to save people some time googling how to upgrade the python package
=> suggest upgrade command in message

.github/workflows/test-build-publish.yml, bin/versionCheck.sh, terrawrap/version.py
Also check the bin directory and use the right envvar to compare against.
=> Fix: Version Check

terrawrap/utils/config.py, terrawrap/version.py
This broke when we upgraded to latest python-hcl2
=> Fix bug caused by python-hcl2 upgrade

terrawrap/utils/cli.py, terrawrap/version.py
Noticed this new string where Terraform sometimes fails to pull down plugins.
=> Fix: Add Another Retry String

terrawrap/utils/collection_utils.py, terrawrap/version.py
This doesn't appear to be used anywhere, and it's failing the lint check, so getting rid of it.
=> Fix: Lint Error

terrawrap/utils/cli.py, terrawrap/version.py
Quick PR - Adding some logger messages to investigate how `graph_apply` executes `_post_to_audit_api_url`
=> AT 6517 | Add logger messages to help debug `graph_apply`

terrawrap/models/pipeline_entry.py, terrawrap/version.py
Potential solution to terraform apply pipeline not sending data to Audit API
=> Add path to `pipeline_entry`'s `execute_command`

terrawrap/utils/cli.py, terrawrap/version.py
Converting stdout to a string for easier parsing in the API
=> Update TF Audit `output` field

README.md, terrawrap/models/wrapper_config.py, terrawrap/utils/config.py, terrawrap/version.py, test/unit/test_config.py
https://amplify-education.atlassian.net/browse/AT-13020
=> AT-13020: add use_lockfile support
