- terrawrap/utils/cli.py
- terrawrap/version.py
Apparently `readline()` is a blocking call and will not return until it
reads a whole line. Changing this to `read(1)` means that we read and
print one byte at a time, and we also ignore the io-blocking put in
place when the process waits for input. This fixes the issues with input
prompts showing up late.
Some more discussion of the issue here:
https://stackoverflow.com/questions/375427/non-blocking-read-on-a-subprocess-pipe-in-python
Also added flush=True to the print command to force flushing of the
buffer.
> Fix IO Blocking

- .remarkrc
- README.md
- bin/tf
- package-lock.json
- package.json
- requirements.pip
- terrawrap/models/wrapper_config.py
- terrawrap/utils/config.py
- terrawrap/version.py
- test/unit/test_config.py
- tox.ini
Adds support for a `backends` section to `.tf_wrapper` 
```yml
backends:
s3:
region:
role_arn:
bucket:
dynamodb_table:
```
The available options are a subset of https://www.terraform.io/docs/backends/types/s3.html#configuration-variables. Will add support for the remaining options in a future PR. `S3` is also the only available backend type but we plan to support other backend types in the future as well.
The above options control which `-backend-config` arguments are generated when running Terraform commands. Each key/value pair corresponds to an additional flag in the form of `-backend-config=key=value`. See https://www.terraform.io/docs/backends/config.html#partial-configuration for more info about this flag
> Add s3 backend config to .tf_wrapper

- bin/plan_check
- terrawrap/version.py
The plan check would sometimes pick up the wrong directories when using `--modified-only` if a modified directory path was a substring of the root directory even if that directory was not a child. For example:
root directory: /foo/bar
modified directory: /foo/bar2
in the above case, `/foo/bar2` is not a child of the root directory so we shouldn't run plan on it even if some files under it have been modified. `/foo/bar2` is a substring of `/foo/bar` though and this would cause the plan_check to run plan on that directory incorrectly
> Fix bug in plan check when directory path is a prefix of another

- bin/tf
- terrawrap/version.py
Terraform 0.12 has importing variables from auto tf vars files without
explicitly declaring them a warning and plans to deprecate them in a
future release. The recommended 'solution' is to instead pass these
global variables as envvars.
> AT-2000 Envvars Instead of Variable Files

- bin/tf_apply
- package-lock.json
- terrawrap/models/pipeline.py
- terrawrap/models/pipeline_entry.py
- terrawrap/version.py
- test/unit/test_pipeline.py
- test/unit/test_pipeline_entry.py
Added a `--print-only-changes` option to tf_apply, that will change the
behavior of tf_apply such that it only prints Terraform output for
directories that actually changed.
Additionally, tf_apply will now not apply a directory if the plan comes
back clean for it.
Additionally, tf_apply will now run init and the desired command in one
operation, which should make applies overall faster and reduce some
needless printing that was going on.
> Optionally Allow Less Printing for tf_apply

- terrawrap/models/wrapper_config.py
- terrawrap/version.py
This is needed so checks won't fail on PRs. Pulled out to allow for testing
> Add depends on field to wrapper config obj

- bin/tf
- terrawrap/version.py
Fixes this error when getting a state exception from terraform and being unable to parse out the lock id from the error message
```
Traceback (most recent call last):
File "/Users/aoskotsky/.virtualenvs/python3/bin/tf", line 257, in <module>
handler()
File "/Users/aoskotsky/.virtualenvs/python3/bin/tf", line 252, in handler
additional_envvars=additional_envvars
File "/Users/aoskotsky/.virtualenvs/python3/bin/tf", line 106, in exec_tf_command
if tf_unlock(error, path, LOCK_TIMEOUT):
File "/Users/aoskotsky/.virtualenvs/python3/bin/tf", line 123, in tf_unlock
lock_id = re.search(r'[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}', error).group()
AttributeError: 'NoneType' object has no attribute 'group'
```
> Gracefully handle being unable to read the lock id from error messages

- bin/graph_apply
- terrawrap/models/graph.py
- terrawrap/version.py
* graph_apply now returns a non-0 exit code if any paths fail
* graph_apply now prints out the paths that failed and the paths that were skipped from the bin script to avoid duplicates
> At 2966/terraform pipeline conversion

- bin/tf
- terrawrap/models/graph.py
- terrawrap/utils/config.py
- terrawrap/utils/dynamodb.py
- terrawrap/utils/graph.py
- terrawrap/utils/path.py
- terrawrap/version.py
- test/unit/test_apply_graph.py
Two fixes here... The DynamoDB unlock functionality would fail when
called from repos that are not called terraform-config, so broke out the
function for figuring out the backend state path so it can be reused.
I also added additional error handling where we delete the lock if the
state file is deleted.
> BugFix: DynamoDB Unlock

- terrawrap/models/pipeline_entry.py
- terrawrap/version.py
- test/unit/test_pipeline_entry.py
Simplify the handling for the plan operation so that it only happens
for apply operation and doesn't block destroy from running.
> BugFix: Correctly Handle Destroy Operation in tf_apply

- bin/plan_check
- terrawrap/utils/plugin_download.py
- terrawrap/version.py
This should update the plan_check command to print a summary of all directories with IAM changes and Terraform failures at the end of the command.
The new output will look something like:
```
General Terraform failures detected. Check the output above and please resolve any issues.
Directories with Terraform failures:
/home/jconstance/workspace/terraform-config/config/aws/amplify-devops-testing/general/astrotools/db_refresh
IAM changes have been detected. If this is intended, please contact the DevOps team to merge.
Directories with IAM changes:
/home/jconstance/workspace/terraform-config/config/aws/amplify-devops-testing/general/iam
```
> Update plan_check to Print IAM and Error Directories

- requirements.pip
- terrawrap/version.py
This fixes some parsing errors with the latest version of Terraform.
> BugFix: Bump python-hcl2 Version

- terrawrap/models/graph_entry.py
- terrawrap/version.py
This fixes a bug where we try to read SSM params for directories that we don't plan to execute because they are outside the root directory that's being applied
> Terrawrap shouldn't init env vars unless it execute the directory

- bin/tf
- terrawrap/version.py
We already delete the .terraform directory on init, so we should also
delete the lock file. We can make both behaviors configurable later on.
> Delete Terraform Lock Files

- CHANGELOG.md
- requirements.pip
- terrawrap/version.py
I have created PR in [terraform-config](https://github.com/amplify-education/terraform-config/pull/6186/files)
In which trying to update the python dependencies. And this update shows [conflicts](https://mhcskylightjenkins-build.aws.wgen.net/jenkins/view/Sandbox/job/sandbox-terraform-create/1296/console)
So set the same PyYAML version as in [astrotools](https://github.com/amplify-education/astrotools_tools/blob/master/requirements.pip#L8)
> Update PyYAML version

- CHANGELOG.md
- terrawrap/utils/config.py
- terrawrap/version.py
Small fix for handling such error
```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.7.10/bin/graph_apply", line 123, in <module>
main()
File "/root/.pyenv/versions/3.7.10/bin/graph_apply", line 68, in main
graph, post_graph = walk_and_graph_directory(config_dir, wrapper_config_dict)
File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/terrawrap/utils/config.py", line 156, in walk_and_graph_directory
graph_wrapper_dependencies(root, config_dict, single_config_dependency_graph, visited)
File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/terrawrap/utils/config.py", line 255, in graph_wrapper_dependencies
graph_wrapper_dependencies(predecessor, config_dict, graph, visited)
File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/terrawrap/utils/co …
```
> BugFix: Fix parsing of the wrap file config

- bin/plan_check
- terrawrap/version.py
Apparently, Terraform 0.15 no longer allows -lock=false for the init
command, so we cannot pass it as an argument in plan_check anymore. So
instead only pass it when we are running the actual plan command.
-lock=false apparently never did anything for init in the first place,
so it should be safe to remove this entirely without trying to do some
kind of version check.
> AT-4667 Fix Plan Check for Terraform 0.15

- bin/graph_apply
- requirements.pip
- terrawrap/models/graph.py
- terrawrap/models/graph_entry.py
- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
- test/unit/test_graph_entry.py
Removed the plan and apply logic from graph_apply. Instead, we will always run apply and use the yes command to auto accept the prompt so that we still get a proper plan output from the command. This will fix the issue where the graph_apply would occasionally run into a transient error when applying, but then would fail again because the plan it was trying to apply was out of date.
Also tried to improve the output from graph_apply by making sure that the directory that finished running was printed along without the output, as this was sometimes unclear...
Also some minor formatting and lint fixes.
> Fix: Graph Apply Retries

- terrawrap/models/wrapper_config.py
- terrawrap/version.py
It looks like the more recent version of JSONS is causing our backend configs to be parsed more strictly, and because they are frequently missing some of these fields, JSONS would be unable to parse them correctly.
So, let's update the model a bit to reflect reality...
> Fix: JSONS Error

- bin/plan_check
- terrawrap/version.py
- test-requirements.pip
The latest version of Terraform will evaluate data sources as print out any diffs that it finds separately, with a note that the Terraform plan might affect those resources.
This change will ignore the output of the plan command in the plan_check until we get to the actual changes that Terraform intends to make, which might include those IAM resources that it warned about above. If the resources are actually included there, then they will be changed and it would be appropriate to flag the plan. If they aren't actually included there, the Terraform engine has decided that the config is sufficiently close that no changes are necessary and we shouldn't flag the plan.
> Fix: Ignore State Warnings

- .github/workflows/test-build-publish.yml
We don't tag releases, so don't do this copypasta...
Also allow dupes to TestPyPi, because that doesn't matter.
> Fix: Bad If on PyPi

- bin/backend_check
- terrawrap/models/wrapper_config.py
- terrawrap/utils/config.py
- terrawrap/utils/plugin_download.py
- terrawrap/version.py
The root seems to be that we were using ProcessPool and not ThreadPool. There doesn't seem to be a particularly good reason why we were doing that, so just switching to ThreadPool resolved that.
Also a few other little fixes sprinkled in as I was testing this against terraform-config...
> Fix: Backend Check Under Python 3.9

- terrawrap/utils/config.py
- terrawrap/version.py
- test/helpers/mock_directory/config/.tf_wrapper
- test/unit/test_config.py
Python's Popen doesn't tolerate integers, booleans, etc as envvars. Instead they must be strings or file objects. So just convert the text-based envvars to always be strings.
> Fix: Convert Envvars to String

- bin/tf
- terrawrap/models/graph_entry.py
- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
Adding path option to execute_command to pass directory path to terraform-audit-api. Previously was sending first argument in command (usually just `terraform`, changed to actual path).
Ex. `config/aws/amplify-devops/devops/astrotools/terraform_audit_api`
> Fixing terraform-audit-api directory path

- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
Updating `_post_to_audit_api_url` to use `get_git_root` to trim root off of posted directory. Also removed exception throwing when terrawrap fails to post to audit API
> Fix `terraform-audit-api` Directory Bug

- terrawrap/models/graph_entry.py
- terrawrap/version.py
See JIRA for more information. 
Adding `audit_api_url` and `cwd`(path) to graph_entry.execute's `execute_command`. Prior to these changes, when running graph_apply, no data would be sent to terraform-audit-api since no url was provided.
> AT-6413 | Add `audit_api_url` and `cwd` parameters to graph_entry

- pylintrc
- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
See [JIRA](https://amplify-education.atlassian.net/browse/AT-6519) for more info.
Updating `execute_command` to send data twice per run, once to create an entry in terraform-audit-api's DynamoDB table with status `In Progress`, and once more after the command is executed to update the status and output. 
These changes depend on the following PRs:
- [Rename `audit_api_url`](https://amplify-education.atlassian.net/browse/AT-6519)
- [Update Audit API](https://github.com/amplify-education/terraform-audit-api/pull/14)
- [Rename `timestamp`](https://github.com/amplify-education/terraform-config/pull/12102)
All PRs should be merged around the same time to avoid any errors.
> AT 6519 | Add Support for `In Progress` Status

- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
Quick PR - Removing this so terrawrap won't unexpectedly error out while working on fixing API
> Fix: Temporarily remove Audit API calls from `execute_command`

- .github/workflows/test-build-publish.yml
- README.md
- setup.py
- terrawrap/version.py
- tox.ini
Python3.6 was already EOL'd so no one should be using it. This is to update the dependancies and linters/tests so we don't test for that version anymore.
This is also required for the following [PR](https://github.com/amplify-education/terrawrap/pull/138) - implementation using features only available in 3.7+.
> Phase out `python3.6`

- terrawrap/utils/cli.py
- terrawrap/version.py
Small bug fix addressing this [error](https://app.datadoghq.com/logs?query=service%3Aterraform-audit-api&event=AQAAAYFDfBfHyO4qRQAAAABBWUZEZkRYX0FBQldlODVPdUJ1ZkF3QU4&index=&from_ts=1654693778665&to_ts=1654694678665&live=true) in `terraform-audit-api` caused by `_post_audit_info`. Apparently no user is being set, so reverting back to previous statement.
> Fix: Update `user` declaration

- terrawrap/utils/cli.py
- terrawrap/version.py
Should now handle any exceptions raised when getpass.getuser is called by AWS
> Fix: Update user declaration in `_post_audit_info`

- terrawrap/utils/cli.py
- terrawrap/version.py
Minor fix - making sure that `execute_command` updates the entry in `terraform-audit-api` even if there is a timeout error.
> Fix: Update Audit API if `execute command` times out

- requirements.pip
- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
Add `AWSRequestsAuth` to terrawrap when calling API. Based on new `ResourcePolicy` in `TF Audit API` defined in this [PR](https://github.com/amplify-education/terraform-audit-api/pull/16).
> Update terrawrap to use IAM auth when calling `TF Audit API`

- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
Quick fix - Addressing this recurring [error](https://app.datadoghq.com/logs?query=service%3Aterraform-audit-api&event=AQAAAYHTt7sLylccHQAAAABBWUhUdDl2OEFBRHBDWng3bWZsR0xnQVY&index=&from_ts=1657100204428&to_ts=1657114604428&live=true) in `TF Audit API`. Previously was posting an element with `None` type causing a serialization error on the API end.
> Fix: Update TF Audit API post request body

- terrawrap/utils/cli.py
- terrawrap/version.py
- test/unit/test_cli.py
Depends on this [PR](https://github.com/amplify-education/terraform-audit-api/pull/18)
Removing the no longer needed parameter run_by from the TF Audit API call in terrawrap.
> AT 6802 | Remove `run_by` parameter from `_post_audit_info`

- terrawrap/utils/cli.py
- terrawrap/utils/plugin_download.py
- terrawrap/version.py
- test/unit/test_plugin_download.py
Converting from milliseconds to seconds - addressing this [issue](https://app.datadoghq.com/logs?query=application%3Aterraform-audit-api&cols=host%2Cservice&event=AQAAAYJZqfQLRzkNVgAAAABBWUpacWkyRkFBQnpheUZIa1pKTzVBQUc&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1659354401649&to_ts=1659368801649&live=true) where the `start_time` value is rounded since it is too large
> Update TF Audit API `start_time` field

- terrawrap/utils/cli.py
- terrawrap/version.py
Updating terrawrap so it only sends data to TF Audit API for `apply` runs (not `init` or `plan`).
> Fix TF Audit interaction

- pylintrc
- terrawrap/utils/cli.py
- terrawrap/utils/plugin_download.py
- terrawrap/utils/version.py
- terrawrap/version.py
- test/unit/test_cli.py
This error string sppears in the unable to acquire state lock error message, and network errors superseed state lock errors, so graph apply could end up in an infinite loop retrying the directory until the creds expired.
> Fix: Quick Change to Fix Auto Unlock

- bin/plan_check
- terrawrap/version.py
SCPs are essentially IAM policies that get applied across accounts, so we should treat them like IAM resources in terms of requiring additional approvals.
> Feat: Add SCPs to Plan Check

- CHANGELOG.md
- terrawrap/utils/git_utils.py
- terrawrap/version.py
- test/unit/test_git.py
- test/unit/test_version.py
- tox.ini
Use merge base when calculating diff against master to avoid including extraneous changes.
Also remove python3.6 from tox config. We dropped support for python3.6 some time ago
> Change plan_check --modified-only to diff against merge base

- terrawrap/models/graph_entry.py
- terrawrap/version.py
There's an issue with how `terrawrap` and `TF Audit` that causes duplicate apply data to be stored (see [example](https://tfaudit.devops.amplify.com/history/+config+aws+litco-dev+us-west-2+ci+mclass+ras-autotests+rasberi-export-pdf-autotests)). 
I intended on rewriting parts of terrawrap to address this, but turns out removing the interaction between the API and terrawrap inside `graph_entry.py` should do the trick.
> Remove `TF Audit` calls from graph_entry

- bin/tf
- terrawrap/version.py
We're going to start using these in our environment, so no longer automatically delete them.
> AT-10360 No Longer Delete Terraform Lock Files

- terrawrap/utils/path.py
- terrawrap/version.py
- test/unit/test_path.py
When running `tf init`, terrawrap wasn't able to match regex to my remotes (both SSH and HTTPS). 
Turns out my git installation is translated to polish, so `git remote show origin -n` shows
`Adres do pobierania: https://github.com/amplify-education/terraform-config.git`
instead of
`Fetch URL https://github.com/amplify-education/terraform-config.git`
The regex is looking for the `URL` phrase which is absent in my case, hence the issue.
> utils/path.py - fix `GIT_REPO_REGEX` and `calc_repo_path`

- bin/tf
- terrawrap/version.py
Let's not bother people with the confirmation prompt for import and
the deleting of the init dir when they are just trying to look at
the help page.
> Ignore Extra Handling for Help

- terrawrap/utils/config.py
- terrawrap/version.py
- test/unit/test_config.py
Now that we encourage people to fix to a specific version of plugins,
this will make the upgrade process easier by automatically pulling in
the new version when they init the directory.
> Always Upgrade on Init
